- name: Reboot
  shell: sleep 2 && shutdown -r now "Ansible updates triggered"
  async: 1
  poll: 0
  ignore_errors: true

- name: Restart lightdm
  service:
    enabled: true
    name: lightdm
    state: restarted

- name: Delete Chrome Singleton
  file:
    path: "/home/{{ autostart_user }}/.config/chromium/Singleton*"
    state: absent

- name: Restart network
  service:
    name: dhcpcd
    state: restarted